### ISSUE TITLE
Refactor hardcoded path to variable

### ISSUE THREAD

**Issue by lindbergan** [dasovm/olga#2]
Change hardcoded string (path): 

```
if not os.path.exists('./stock_data/'):
        os.makedirs('./stock_data/')
    df.to_csv('./stock_data/' + ticker + '.csv')
```

To a variable so that changing path for ./stock_data/ later in the project is feasible
Should instead be declared as:

```
class Constant():
    stock_path = './stock_data/'
```

``` Constant.stock_path
>>> ./stock_data/
```

and accessed as something like this:

```
path = Constant.stock_path
if not os.path.exists(path):
        os.makedirs(path)
    df.to_csv(path + ticker + '.csv')
```

**Comment by dasovm** [comment]
[Done](https://github.com/dasovm/olga/commit/fda2bcfd521c91d01e6f08ad484a55cb8fc8eca3)
